const BlogData = [
  {
    id: 1,
    date: "January 01, 2020",
    catgeory: "Business ",
    title: "Tips to Improve Service Quality at Your Hotel",
    cover: "/images/singlepage/blog-1.jpg",
    para: "We can’t all be celebrities, CEO’s, or royalty, but treat every guest like a VIP and we guarantee it will be a memorably positive experience they will want to repeat.  Coach your staff to be attentive, responsive and have a sense of urgency for everyone, regardless of their “status”.  In return, your guests will reward you with their patronage, loyalty and – even better – referrals.  An added bonus: when guests are feeling wonderful and special, secondary factors that may pop-up become much more minor (e.g., a small room, mediocre location, etc.)..",
    desc: "Recent studies show that employee turnover is among the highest in the hospitality industry with the average employee turnover in the US reaching 31 percent and as high as 34 percent in the UK. This constant churn is very disruptive and leads to loss of productivity, low morale and poor customer service – not to mention hurting the bottom line. To combat this epidemic, leading hotels are rethinking their onboarding approach.Onboarding surveys by the Center for Creative Leadership reveal that new employees who attended a well structured onboarding program were 69% more likely to remain at a company for up to three years.  While previous new-employee initiation programs were one day affairs, today a strong onboarding strategy extends past the first day/week/month to include an on-going approach that will accompany the employee throughout the employment lifetime and support them to achieve better job performance.",
  },
  {
    id: 2,
    date: "January 15, 2021",
    catgeory: "Traveling",
    title: "Best Resorts Near Guwahati",
    cover: "/images/singlepage/blog-2.jpg",
    para: "Guwahati is a pristine city in Assam where one can find serenity and calmness amongst the mountains and lanes. There are many beautiful places to visit in Guwahati like Kamakhya Temple, Umananda Temple, Assam State Museum, Guwahati Zoo, Nehru Park, Alfresco Grand, Pobitora wildlife sanctuary, Guwahati Planetarium, etc. With so many places to visit, Guwahati is an ideal destination for vacation, and while we are on the topic of vacations, we cannot leave behind one of the most important prerequisites of a good trip – good accommodation!",
    desc: "The royal view resort is situated at the perfect location in the heart of the city which is accessible to all sightseeing places which are nearby.. All rooms are equipped with basic amenities like a kettle, hairdryer, free Wifi, TV, shower, attached bathroom, study desk and much more. They are also offering you a complimentary Asian breakfast. The other facilities that you can enjoy in royal view resort are car hire, free parking, on-site restaurant, off-site hiking, laundry, iron service and much more. The entire resort is having CCTV cameras that are working 24 hours. It is one of the best resorts near Guwahati.",
  },
  {
    id: 3,
    date: "January 21, 2019",
    catgeory: "Developement",
    title: "INNOVATIVE LUXURY HOTEL DESIGN IDEAS & CONCEPTS",
    cover: "/images/singlepage/blog-3.jpg",
    para: "Most innovative hotels are far more than the sum of their parts – today’s guests want their hotel to be a destination; an escape into another world of fine dining, wellness and adventure experiences, personalised service and great memories. As a result, hotels are creating exclusive hotel design concepts to cater to these changing needs through innovative technology, green spaces, personalised activities and more, creating a fully rounded and powerful guest experience..",
    desc: "This is a fantastic time for boutique hotels to embrace their character, quirks and eccentricities! Travelers aren’t looking for more of the same, they want adventure, newness and uniqueness – they want something to really write home about. They want their vacation to be different to everyone else’s, and that means creating something really unique and compelling in your luxury hotel.Whether it’s smart tech that no-one has ever seen before, running your hotel completely off-grid by creating a completely self-sustaining environment, or incorporating your unique and quirky history into your design, the goal is to create memories that last a lifetime.If you’re looking for inspiration: Treehotel in Sweden combines stunning architecture with untouched nature, and is about as close to living in a tree as one could hope to get. The Hôtel de Glace in Quebec is built entirely out of snow and ice, and the Yunak Evleri in Turkey offers 5-star luxury cave living.",
  },
  {
    id: 4,
    date: "January 30, 2019",
    catgeory: " Motion Designer",
    title: "Wellness Initiatives and Luxurious Bathrooms",
    cover: "/images/singlepage/blog-4.jpg",
    para: "Today’s guests want to feel like the best version of themselves when they are on vacation – they want to feel pampered, healthy and re-energised. This trend is not only reflected in on-site spa facilities, but also in the luxury and spa-like attention to detail in private bathrooms, the ability to access yoga, meditation and nature excursions on-site, and the incorporation of health options into food and beverage menus.Luxury hotel room design now incorporates en-suite bathrooms as focal features rather than the functional and necessary space they used to be. New hotel design ideas are being integrated, such as waterfall and steam showers, oversized bathtubs, luxurious towels and toiletries, and striking private views. When delivered correctly, like at the Silo in Cape Town, the Areias Do Seixo in Portugal or the Dunton Hot Springs in Colorado, bathrooms can become a sanctuary and a real draw for guests looking for extraordinary experiences.",
    desc: "Gone are the days when every hotel room was homogenous, where you could be in Rome, London, Chicago or Nairobi and step into a space that was as familiar as it was boring. Today, local experiences are a huge trend, influencing every aspect of a hotel’s design and services. This includes using local art, materials and décor to make luxury hotel rooms and spaces reflect local culture, local produce and cuisine on the menu, and sightseeing tours for local events and points of interest. Just take a look at Casa Angelina’s Instagram account and you can’t imagine you’re anywhere other than the Amalfi Coast!.",
  },
  {
    id: 5,
    date: "January 10, 2022",
    catgeory: "Content Writing",
    title: "Going Green for the Planet",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Developing your green credentials is another trend not to be ignored when developing luxury hotel concepts. 87% of travellers actively look for green hotels when planning business or leisure trips while 69% believe that sustainable travel is important. The important thing to remember is that guests want their stay to be as sustainable and eco-friendly as possible, while still retaining the luxury and special elements of an exceptional experience. ",
    desc: "We dive further into green hotels here, as green design holds great benefits for hotels – from water, waste and energy use reductions through to local and organic integrations. Take a look at the Fogo Island Inn in Canada or the Aquila Eco Lodges in Australia to see some exceptional combinations of sustainability and luxury living that are friendly to the planet while delivering compelling design. You can find more about our hotel sustainability services here.",
  },
  {
    id: 6,
    date: "January 18, 2021",
    catgeory: "Feel Like Home",
    title: "luxury hotel room design, just like home",
    cover: "/images/singlepage/blog-6.jpg",
    para: "When today’s guests travel, they want to feel at home wherever they go. In many cases, guests also need the reassurance that they will have access to the practical amenities that they need (the lack of which is a nightmare for any parents of young children!). This concept focuses on creating a luxury dream home; a fantasy space where you feel welcome and relaxed, and are able to enjoy all the upsides of a getaway while still having all the practical benefits of a private home..",
    desc: "Elements of the home away from home luxury hotel concept includes warm and cozy features, eclectic furnishings, fireplaces, the ability to catch your favorite show or play your favorite music, personalized food services, and even flexible layouts for furnishings. Nothing is cookie-cutter, yet nothing is overwhelming – everything is about mental and physical comfort. Hotels that exude this design concept include the common areas and rooms of the Le Roch Hotel & Spa in Paris and the Auberge Saint-Antoine in Quebec.  ",
  },
  {
    id: 6,
    date: "January 12, 2014",
    catgeory: "Design Matters",
    title: "Biophilic DesignSmart Flexible Visiting Card",
    cover: "/images/singlepage/blog-1.jpg",
    para: "Innovative hotel design concepts show how easy and beneficial it is to bring these elements into hotel design in hundreds of different ways, from blurring the boundaries between indoor and outdoor spaces and maximizing natural lighting to using raw natural materials, natural ventilation, organic building materials and landscaping design to make hotels a part of nature.",
    desc: "Because biophilic design can be implemented in so many different ways, it opens a new space for creativity and uniqueness for boutique hotels. Great examples include the Bosco Verticale in Milan, and the Mirrorcube at Treehotel in Sweden. We explore more about biophilic design and how it can improve your business’s bottom line in this blog post.",
  },
  {
    id: 7,
    date: "January 30, 2019",
    catgeory: "Travel in Best Hotels",
    title: "Bleisure Travel",
    cover: "/images/singlepage/blog-4.jpg",
    para: "In the past, people travelled for business or pleasure – but today, they travel for both. Business travelers want the option of getting to know the area and sights in the towns and cities they visit, and need easy access to activities that they can fit in around their business schedule. Similarly, many people who travel for leisure still need to be able to stay in contact with their business lives, and need reliable and easy access to facilities that allow them to communicate, collaborate and fulfill their duties wherever they are.",
    desc: "Simple features including high-speed Wi-Fi access, in-room workstations, meeting rooms, function halls and dining spaces are all essential in a time where work and leisure lives can’t be separated so easily.  The Fairlane Hotel in downtown Nashville offers numerous workspaces, all inspired by Mid-century modern design, to ensure bleisure travelers have an enjoyable work experience. In addition to their meeting areas, they’ve added communal work tables in the lobby with its terrazzo flooring, wood paneling, brass elements and natural greenery.",
  },
  {
    id: 8,
    date: "January 10, 2022",
    catgeory: "Technology in Hotels",
    title: "Tech, Tech, Tech",
    cover: "/images/singlepage/blog-5.jpg",
    para: "We live, work and travel in a world dominated by technology, so it makes sense to embrace this trend as one of the most powerful influences on luxury hotel design concepts today. Today’s boutique hotels are more operationally integrated than ever before, using the power of apps to let guests check in and out, make bookings for restaurants and activities, and communicate directly with staff. Tech also allows guests to personalize their room to their own preferences according to lighting, air flow, heating and more..",
    desc: "Even if your hotel is designed to be a space where guests can disconnect and switch off, the right technology can help you achieve this more effectively and affordably. Smart tech systems that automatically adjust lighting and heating in rooms based on preferences and occupation reduce energy wastage, while smart operating systems help relieve staff of repetitive administration duties in order to better serve guests. All the while, they still play a vital role in design effect and ambiance creation. You can find more about our hotel technology consulting services here..",
  },
]

export default BlogData
